<div class="banner owl-carousel">
    <?php $banners = $block->getBanners(); ?>
    <?php foreach ($banners as $banner) : ?>
        <div class="item">
            <img class="banner-image" src="<?php echo $banner; ?>" alt="Banner">
        </div>
    <?php endforeach; ?>
</div>

<script>
    require(['jquery', 'owlCarousel'], function($) {
        $(document).ready(function() {
            $(".banner").owlCarousel({
                items: 1,
                loop: true,
                autoplay: true,
                autoplayTimeout: 3000,
                autoplayHoverPause: true,
                autoWidth: true,
                center: true
            });
        });
    });
</script>
